### ISSUE TITLE
Sign ps1 (PowerShell script) files

### ISSUE THREAD

**Issue by chasewallis** [develar/osslsigncode#2]
I need to sign ps1 files, but I don't want to have go to a windows machine just to sign a script. Is it possible to modify this program to also sign ps1 files?

A signed ps1 file would just have the signature appended to the end of the script:

```
# SIG # Begin signature block
# thesignaturewouldgohere
# ...
# SIG # End signature block
```

**Comment by develar** [comment]
@chasewallis Active maintainer of osslsigncode — https://github.com/mtrojnar/osslsigncode Please file issue there.
